# Generated by Django 3.0.5 on 2020-04-18 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Блюдо')),
                ('wines/', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Еда',
            },
        ),
        migrations.CreateModel(
            name='GrapeSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('wines/', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Cорт Винограда',
                'verbose_name_plural': 'Сорта Винограда',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('wines/', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('year', models.PositiveIntegerField(default=0, verbose_name='Год разлива')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wines.Category', verbose_name='Категория')),
                ('grape_sort', models.ManyToManyField(to='wines.GrapeSort', verbose_name='Сорт')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wines.Reviews', verbose_name='Родитель')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.Wine', verbose_name='вино')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.RatingStar', verbose_name='Звезда')),
                ('wine', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='wines.Wine', verbose_name='Вино')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
    ]
