# Generated by Django 3.0.5 on 2020-04-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='url',
        ),
        migrations.RemoveField(
            model_name='food',
            name='wines/',
        ),
        migrations.RemoveField(
            model_name='grapesort',
            name='wines/',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='wines/',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(null=True, upload_to='food/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='food',
            name='wine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wines.Wine', verbose_name='Вино'),
        ),
        migrations.AddField(
            model_name='grapesort',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.Wine', verbose_name='Вино'),
        ),
    ]
