# Generated by Django 3.0.5 on 2020-04-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_auto_20200424_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='wine',
        ),
        migrations.AddField(
            model_name='food',
            name='wine',
            field=models.ManyToManyField(to='wines.Wine', verbose_name='Вино'),
        ),
    ]
