# Generated by Django 3.0.3 on 2020-04-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_auto_20200425_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wines.Wine', verbose_name='Вино'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape_sort',
            field=models.ManyToManyField(related_name='grape', to='wines.GrapeSort', verbose_name='Сорт'),
        ),
    ]
